# Generated by Django 5.2.5 on 2025-09-11 03:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Volunteer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('volunteer_name', models.CharField(default='0', max_length=100)),
                ('volunteer_email', models.CharField(default='0', max_length=100, unique=True)),
                ('volunteer_pass', models.CharField(default='0', max_length=100)),
                ('volunteer_role', models.CharField(choices=[('admin', 'Admin'), ('leader', 'Group Leader'), ('member', 'Member')], max_length=100)),
                ('volunteer_regi_datetime', models.DateTimeField(auto_now_add=True)),
                ('volunteer_update_regi_datetime', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
