# Generated by Django 5.2.5 on 2025-09-11 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='volunteer',
            name='volunteer_role',
            field=models.CharField(choices=[('Admin', 'Admin'), ('Group Leader', 'Group Leader'), ('Member', 'Member')], max_length=100),
        ),
    ]
