# Generated by Django 5.2.5 on 2025-09-12 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_alter_volunteer_volunteer_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='volunteer',
            name='volunteer_contact',
            field=models.IntegerField(default='0'),
        ),
    ]
