# Generated by Django 5.2.5 on 2025-09-12 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_volunteer_volunteer_contact'),
    ]

    operations = [
        migrations.AlterField(
            model_name='volunteer',
            name='volunteer_contact',
            field=models.CharField(default='0', max_length=10),
        ),
    ]
