# Generated by Django 5.2.5 on 2025-09-12 17:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0004_alter_volunteer_volunteer_contact'),
    ]

    operations = [
        migrations.CreateModel(
            name='Groupcreate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group_name', models.CharField(default='0', max_length=100, unique=True)),
                ('group_regi_date', models.DateField(auto_now_add=True)),
                ('group_update_regi_date', models.DateField(auto_now=True)),
                ('leader', models.ForeignKey(limit_choices_to={'volunteer_role': 'Group Leader'}, on_delete=django.db.models.deletion.CASCADE, related_name='leaders_of_group', to='dashboard.volunteer')),
            ],
        ),
    ]
