# Generated by Django 5.2.5 on 2025-09-17 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0005_groupcreate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='volunteer',
            name='volunteer_regi_datetime',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='volunteer',
            name='volunteer_update_regi_datetime',
            field=models.DateField(auto_now=True),
        ),
    ]
