# Generated by Django 5.2.5 on 2025-09-21 09:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0006_alter_volunteer_volunteer_regi_datetime_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Volunteers_group',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group_role', models.CharField(choices=[('Member', 'Member')], max_length=100)),
                ('groupcreate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='volunteers_group_name', to='dashboard.groupcreate')),
                ('volunteer', models.ForeignKey(limit_choices_to={'volunteer_role': 'Member'}, on_delete=django.db.models.deletion.CASCADE, related_name='name_of_volunteer', to='dashboard.volunteer')),
            ],
        ),
    ]
