# Generated by Django 5.2.5 on 2025-10-02 20:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0007_volunteers_group'),
    ]

    operations = [
        migrations.AlterField(
            model_name='volunteer',
            name='volunteer_update_regi_datetime',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
