# Generated by Django 5.2.5 on 2025-10-02 20:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0008_alter_volunteer_volunteer_update_regi_datetime'),
    ]

    operations = [
        migrations.AlterField(
            model_name='groupcreate',
            name='group_update_regi_date',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
