# Generated by Django 5.2.5 on 2025-10-07 10:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0009_alter_groupcreate_group_update_regi_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='Task_management',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_title', models.CharField(default='0', max_length=100)),
                ('task_description', models.TextField(default='0')),
                ('task_deadline', models.DateField()),
                ('task_created_at', models.DateField(auto_now_add=True)),
                ('task_status', models.CharField(choices=[('Pending', 'Pending'), ('In Progress', 'In Progress'), ('Complete', 'Complete')], max_length=100)),
                ('leader', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='name_of_leader', to='dashboard.groupcreate')),
                ('task_assign_by', models.ForeignKey(limit_choices_to={'volunteer_role': 'Admin'}, on_delete=django.db.models.deletion.CASCADE, related_name='assigned_name', to='dashboard.volunteer')),
            ],
        ),
    ]
