# Generated by Django 5.2.5 on 2025-10-07 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0010_task_management'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task_management',
            name='task_deadline',
            field=models.DateTimeField(),
        ),
    ]
