# Generated by Django 5.2.5 on 2025-10-08 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0011_alter_task_management_task_deadline'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task_management',
            name='task_status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('In Progress', 'In Progress'), ('Complete', 'Complete')], default='Pending', max_length=100),
        ),
    ]
