# Generated by Django 5.2.5 on 2025-10-10 04:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0012_alter_task_management_task_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task_management',
            name='task_status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('In Progress', 'In Progress'), ('Complete', 'Complete'), ('Rejected', 'Rejected')], default='Pending', max_length=100),
        ),
    ]
