# Generated by Django 5.2.5 on 2025-10-10 05:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0013_alter_task_management_task_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='task_management',
            name='task_reject_reason',
            field=models.TextField(blank=True, default='N/A', null=True),
        ),
    ]
