# Generated by Django 5.2.5 on 2025-10-10 06:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0014_task_management_task_reject_reason'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task_management',
            name='leader',
        ),
        migrations.AddField(
            model_name='task_management',
            name='group',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='name_of_group', to='dashboard.groupcreate'),
            preserve_default=False,
        ),
    ]
