# Generated by Django 5.2.5 on 2025-10-10 06:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0015_remove_task_management_leader_task_management_group'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task_management',
            old_name='group',
            new_name='Group',
        ),
    ]
