# Generated by Django 5.2.5 on 2025-10-27 17:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0016_rename_group_task_management_group'),
    ]

    operations = [
        migrations.CreateModel(
            name='Role_set',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role_name', models.CharField(default='0', max_length=100)),
            ],
        ),
        migrations.AlterField(
            model_name='volunteer',
            name='volunteer_role',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='role_of_volunteer', to='dashboard.role_set'),
        ),
    ]
