# Generated by Django 5.2.5 on 2025-10-27 17:12

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0017_role_set_alter_volunteer_volunteer_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='role_set',
            name='role_regi_datetime',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
