# Generated by Django 5.2.5 on 2025-10-28 09:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0018_role_set_role_regi_datetime'),
    ]

    operations = [
        migrations.AlterField(
            model_name='groupcreate',
            name='leader',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leaders_of_group', to='dashboard.volunteer'),
        ),
    ]
