# Generated by Django 5.2.5 on 2025-10-28 10:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0019_alter_groupcreate_leader'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task_management',
            name='task_assign_by',
        ),
        migrations.RemoveField(
            model_name='task_management',
            name='task_deadline',
        ),
    ]
