# Generated by Django 5.2.5 on 2025-11-09 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0020_remove_task_management_task_assign_by_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notify_type', models.CharField(choices=[('Casual', 'Casual Message'), ('Meeting', 'Meeting Link')], default='Casual', max_length=100)),
                ('title', models.CharField(max_length=500)),
                ('message', models.TextField()),
                ('link', models.URLField(blank=True, null=True)),
                ('notify_created_at', models.DateTimeField(auto_now_add=True)),
                ('is_read', models.BooleanField(default=False)),
            ],
        ),
    ]
