# Generated by Django 5.2.5 on 2025-11-20 21:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0023_alter_notification_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='volunteer',
            name='profile_photo',
            field=models.ImageField(blank=True, null=True, upload_to='uploads/'),
        ),
        migrations.AddField(
            model_name='volunteer',
            name='volunteer_address',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='volunteer',
            name='volunteer_birthday',
            field=models.DateField(blank=True, null=True),
        ),
    ]
