# Generated by Django 5.2.5 on 2025-12-11 06:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0024_volunteer_profile_photo_volunteer_volunteer_address_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sub_task_managemnet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subtask_description', models.TextField(default='0')),
                ('subtask_status', models.CharField(choices=[('Pending', 'Pending'), ('In Progress', 'In Progress'), ('Complete', 'Complete'), ('Rejected', 'Rejected')], default='Pending', max_length=100)),
                ('assigned_subtask_to', models.ForeignKey(limit_choices_to={'volunteer_role': 'Member'}, on_delete=django.db.models.deletion.CASCADE, related_name='name_of_volunteer', to='dashboard.volunteers_group')),
                ('task_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sub_task_title', to='dashboard.task_management')),
            ],
        ),
    ]
