# Generated by Django 5.2.5 on 2025-12-11 10:49

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0025_sub_task_managemnet'),
    ]

    operations = [
        migrations.AddField(
            model_name='sub_task_managemnet',
            name='subtask_created_at',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='sub_task_managemnet',
            name='subtask_updated_at',
            field=models.DateField(auto_now=True),
        ),
    ]
